-- Data Base Link o DBLink

CREATE DATABASE LINK DBL_JAVAPOO
CONNECT TO JAVAPOO IDENTIFIED BY java
USING 'XE';


-- SELECT * FROM EMPLEADO@DBL_JAVAPOO;
-- SELECT * FROM JAVAPOO.EMPLEADO

-- Sinónimos 

CREATE SYNONYM EMPLEADO FOR EMPLEADO@DBL_JAVAPOO;

-- EQUIVALENCIAS
SELECT * FROM GERENTE@DBL_JAVAPOO;
SELECT * FROM EMPLEADO@DBL_JAVAPOO;
SELECT * FROM EMPLEADO;