-- Insert de Clientes
INSERT INTO CLIENTES (NOMBRE, APATERNO, AMATERNO, RFC, FECHA_ALTA) VALUES('Ana', 'Gomez', 'Perez', 'COPA800101', DATE '2023-01-15');
INSERT INTO CLIENTES (NOMBRE, APATERNO, AMATERNO, RFC, FECHA_ALTA) VALUES('Betoo', 'Lopez', 'Rojas', 'LORA900505', DATE '2023-03-20');
INSERT INTO CLIENTES (NOMBRE, APATERNO, AMATERNO, RFC, FECHA_ALTA) VALUES('Carlos', 'Mena', 'Sosa', 'MESO751111', DATE '2024-02-01');
INSERT INTO CLIENTES (NOMBRE, APATERNO, AMATERNO, RFC, FECHA_ALTA) VALUES('Diana', 'Nuñez', 'Vela', 'NUVE881212', DATE '2024-04-10');
INSERT INTO CLIENTES (NOMBRE, APATERNO, AMATERNO, RFC, FECHA_ALTA) VALUES('Elenaa', 'Ortiz', 'Cruz', 'ORCR950707', DATE '2024-06-25');
COMMIT;

SELECT * FROM CLIENTES;
SELECT * FROM CLIENTES_BIT;

UPDATE CLIENTES SET NOMBRE = 'Beto' WHERE ID_CLIENTE = 2;
UPDATE CLIENTES SET NOMBRE = 'Elena' WHERE ID_CLIENTE = 5;
COMMIT;

SELECT * FROM CLIENTES;
SELECT * FROM CLIENTES_BIT;

INSERT INTO TELEFONOS (ID_CLIENTE, TELEFONO) VALUES (1, '5511223344');
INSERT INTO TELEFONOS (ID_CLIENTE, TELEFONO) VALUES (1, '5678904352');
INSERT INTO TELEFONOS (ID_CLIENTE, TELEFONO) VALUES (2, '5544567823');
INSERT INTO TELEFONOS (ID_CLIENTE, TELEFONO) VALUES (4, '5578095621');
COMMIT;

SELECT * FROM TELEFONOS;
SELECT * FROM TELEFONOS_BIT;

SELECT * FROM VIW_CLIENTES_TELEFONOS;
SELECT * FROM MV_CLIENTES_TELEFONOS;


SELECT 
    CLIENTES.ID_CLIENTE,
    TELEFONOS.ID_TELEFONO,
    CLIENTES.NOMBRE || ' ' || CLIENTES.APATERNO || ' ' || CLIENTES.AMATERNO AS NOMBRE_CLIENTE,
    CLIENTES.RFC,
    TELEFONOS.TELEFONO
FROM CLIENTES
LEFT JOIN TELEFONOS ON CLIENTES.ID_CLIENTE = TELEFONOS.ID_CLIENTE
-- INNER JOIN TELEFONOS ON CLIENTES.ID_CLIENTE = TELEFONOS.ID_CLIENTE
-- WHERE TELEFONOS.ID_TELEFONO IS NOT NULL
ORDER BY CLIENTES.NOMBRE, CLIENTES.APATERNO, CLIENTES.AMATERNO;

-- Insertar en facturas desde procedimiento almacenado
VARIABLE v_id_factura NUMBER;
EXECUTE SP_INSERTAR_FACTURA(1, 1500.00, DATE '2023-05-10', :v_id_factura);
PRINT v_id_factura;

VARIABLE v_id_factura NUMBER;
EXECUTE SP_INSERTAR_FACTURA(3, 5000.00, DATE '2024-03-05', :v_id_factura);
PRINT v_id_factura;

VARIABLE v_id_factura NUMBER;
EXECUTE SP_INSERTAR_FACTURA(1, 800.00, DATE '2023-11-20', :v_id_factura);
PRINT v_id_factura;

VARIABLE v_id_factura NUMBER;
EXECUTE SP_INSERTAR_FACTURA(4, 1200.00, DATE '2024-04-25', :v_id_factura);
PRINT v_id_factura;

VARIABLE v_id_factura NUMBER;
EXECUTE SP_INSERTAR_FACTURA(5, 300.00, DATE '2024-06-30', :v_id_factura);
PRINT v_id_factura;


SELECT * FROM FACTURAS;
SELECT * FROM FACTURAS_BIT;


-- Inserte de tabla pagos
VARIABLE v_id_pago NUMBER;
EXECUTE SP_INSERTAR_PAGO(3, 1000.00, DATE '2023-05-15', :v_id_pago);
PRINT v_id_pago;

VARIABLE v_id_pago NUMBER;
EXECUTE SP_INSERTAR_PAGO(3, 500.00, DATE '2023-05-15', :v_id_pago);
PRINT v_id_pago;

VARIABLE v_id_pago NUMBER;
EXECUTE SP_INSERTAR_PAGO(5, 800.00, DATE '2023-11-20', :v_id_pago);
PRINT v_id_pago;

VARIABLE v_id_pago NUMBER;
EXECUTE SP_INSERTAR_PAGO(4, 3000.00, DATE '2024-03-05', :v_id_pago);
PRINT v_id_pago;

VARIABLE v_id_pago NUMBER;
EXECUTE SP_INSERTAR_PAGO(4, 2000.00, DATE '2024-03-05', :v_id_pago);
PRINT v_id_pago;

VARIABLE v_id_pago NUMBER;
EXECUTE SP_INSERTAR_PAGO(6, 1000.00, DATE '2024-04-25', :v_id_pago);
PRINT v_id_pago;

SELECT * FROM PAGOS;
SELECT * FROM PAGOS_BIT;






