-- Vista que trae a todos los clientes con sus teléfonos
CREATE OR REPLACE VIEW VIW_CLIENTES_TELEFONOS AS
SELECT
    CLIENTES.ID_CLIENTE,
    TELEFONOS.ID_TELEFONO,
    CLIENTES.NOMBRE || ' ' || CLIENTES.APATERNO || ' ' || CLIENTES.AMATERNO AS NOMBRE_CLIENTE,
    CLIENTES.RFC,
    TELEFONOS.TELEFONO
FROM CLIENTES
LEFT JOIN TELEFONOS ON CLIENTES.ID_CLIENTE = TELEFONOS.ID_CLIENTE 
ORDER BY CLIENTES.NOMBRE, CLIENTES.APATERNO, CLIENTES.AMATERNO;

-- Vista que trae las facturas con sus pagos
CREATE OR REPLACE VIEW VIW_FACTURAS_PAGOS AS
SELECT 
    F.ID_FACTURA,
    P.ID_PAGO,
    F.FECHA_FACTURA,
    F.FOLIO || '/' || F.ANIO AS FOLIO_COMPLETO,
    F.MONTO_TOTAL AS MONTO_FACTURA,
    P.MONTO AS MONTO_PAGO,
    P.FECHA_PAGO
FROM FACTURAS F
LEFT JOIN PAGOS P ON F.ID_FACTURA = P.ID_FACTURA
ORDER BY F.ID_FACTURA, P.FECHA_PAGO

-- Vista Materrializada del clientes con teléfonos
CREATE MATERIALIZED VIEW MV_CLIENTES_TELEFONOS
BUILD IMMEDIATE
REFRESH COMPLETE
START WITH SYSDATE
NEXT SYSDATE + 1/24
AS
SELECT
    CLIENTES.ID_CLIENTE,
    TELEFONOS.ID_TELEFONO,
    CLIENTES.NOMBRE || ' ' || CLIENTES.APATERNO || ' ' || CLIENTES.AMATERNO AS NOMBRE_CLIENTE,
    CLIENTES.RFC,
    TELEFONOS.TELEFONO
FROM CLIENTES
LEFT JOIN TELEFONOS ON CLIENTES.ID_CLIENTE = TELEFONOS.ID_CLIENTE
ORDER BY CLIENTES.NOMBRE, CLIENTES.APATERNO, CLIENTES.AMATERNO;

